spring:
  application:
    name: spring-batch.batch-app
  profiles:
    active: @spring.profiles.active@
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      fail-fast: true
    task:
      initialize:
        enable: false
  banner:
    location: classpath:banner/banner.txt

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml

management:
  endpoints:
    web:
      exposure:
        include: refresh

---
spring:
  config:
    activate:
      on-profile: default
    import: optional:configserver:http://localhost:8082/config
  flyway:
    enabled: true
    baseline-version: 1
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: ${spring.batch-manage.datasource.jdbc-url}
    user: ${spring.batch-manage.datasource.username}
    password: ${spring.batch-manage.datasource.password}
    schemas: public
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy


---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://localhost:8082/config


---
spring:
  config:
    activate:
      on-profile: qa
    import: optional:configserver:http://localhost:8082/config


---
spring:
  config:
    activate:
      on-profile: stg
    import: optional:configserver:http://localhost:8082/config

---
spring:
  config:
    activate:
      on-profile: prod
    import: optional:configserver:http://localhost:8082/config