spring:
  oracle:
    datasource:
      jdbc-url: jdbc:log4jdbc:oracle:thin:@127.0.0.1:1521:xe
      username: ora
      password: ora
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 2
        connection-test-query: SELECT 1 FROM DUAL
      mybatis:
        config: classpath:mybatis/config/mybatis-config.xml
        mapper-locations: classpath*:com/spring/batch/**/mapper/oracle/*Mapper.xml
  postgres:
    datasource:
      jdbc-url: jdbc:log4jdbc:postgresql://127.0.0.1:5432/batchdb?useUnicode=true&characterEncoding=utf8&escapeSyntaxCallMode=callIfNoReturn
      username: batch
      password: batch
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 2
        connection-test-query: SELECT 1
      mybatis:
        config: classpath:mybatis/config/mybatis-config.xml
        mapper-locations: classpath*:com/spring/batch/**/mapper/postgres/*Mapper.xml