CREATE TABLE ITEM (
    ITEM_ID VARCHAR2(13) NOT NULL,
    ITEM_NAME VARCHAR(500) NOT NULL,
    UNIT_ITEM_ID VARCHAR2(5) NOT NULL,
    UNIT_ITEM_NAME VARCHAR(500) NOT NULL,
    REG_DTS DATE NOT NULL,
    REG_ID VARCHAR2(20) NOT NULL,
    MOD_DTS DATE NOT NULL,
    MOD_ID VARCHAR2(20) NOT NULL,
    CONSTRAINT ITEM_PK PRIMARY KEY (ITEM_ID, UNIT_ITEM_ID)
)